-- CreateEnum
CREATE TYPE "EQUIPAMENT_STATUS" AS ENUM ('WAITING_EVALUATION', 'WAITING_CLIENT_APPROVE', 'WAITING_FOR_REPAIR', 'WAITING_FOR_PARTS', 'WAITING_FOR_WITHDRAWAL', 'FINALIZED');

-- AlterTable
ALTER TABLE "equipaments" ADD COLUMN     "status" "EQUIPAMENT_STATUS" NOT NULL DEFAULT 'WAITING_EVALUATION';
